### ISSUE TITLE
Test Failed at Step 2

### ISSUE THREAD

**Issue by ithinco** [JejomStark/SymbOnStark#1]
Thanks for this great project.

At the step 2, when I ran the test, it first report max_fee error
```
HardhatPluginError: Could not perform invoke on increase_balance:
Got BadRequest while trying to access https://alpha4.starknet.io/gateway/add_transaction. Status code: 500; text: {"code": "StarknetErrorCode.OUT_OF_RANGE_FEE", "message": "max_fee must be bigger than 0.\n0 >= 0"}.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/services/external_api/base_client.py", line 120, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.OUT_OF_RANGE_FEE", "message": "max_fee must be bigger than 0.\n0 >= 0"}
Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.OUT_OF_RANGE_FEE", "message": "max_fee must be bigger than 0.\n0 >= 0"}
```
Then I added the max_fee option ```await contract.invoke("increase_balance", { amount: 10 }, { maxFee: BigInt("1") });```

It reports this error:
```
HardhatPluginError: Could not perform invoke on increase_balance:
Got BadRequest while trying to access https://alpha4.starknet.io/gateway/add_transaction. Status code: 500; text: {"code": "StarknetErrorCode.UNSUPPORTED_SELECTOR_FOR_FEE", "message": "All transactions should go through the __execute__ entrypoint."}.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/services/external_api/base_client.py", line 120, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNSUPPORTED_SELECTOR_FOR_FEE", "message": "All transactions should go through the __execute__ entrypoint."}
Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNSUPPORTED_SELECTOR_FOR_FEE", "message": "All transactions should go through the __execute__ entrypoint."}
```
Any ideas? Thanks.

**Comment by JejomStark** [comment]
I will do some tests. This tutorial was made a while ago
